[package]
name = "tnf_web_server"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
tnf_common = { path = "../common", features = ["server"] }
clients_db = { path = "../clients_db" }
actix-web = "1.0.0"
actix = "0.8.3"
futures = "0.1.27"
lazy_static = "1.3.0"
fo_save_format = { git = "https://github.com/qthree/fo_save_format.git" }
tera = "0.11.20"
serde = "1.0.92"
rsass = "0.9.8"
custom_error = "1.6.0"
percent-encoding = "1.0.1"
arrayvec = "0.4.10"
actix-files = "0.1.2"
